steps:
  build:
    image: coralhl/woodpecker-buildx-plugin
    settings:
      build_args:
        - VERSION=0.22.12
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: coralhl/pocketbase
      platforms:
        - linux/amd64
        - linux/arm64
      tags:
      - latest
      - 0.22.12